import fs from 'node:fs';
import path from 'node:path';
import Papa from 'papaparse';

const srcDir = path.resolve('decks');
const outDir = path.resolve('src/data');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const camelCase = (str) => str.replace(/[-_]([a-z])/g, (g) => g[1].toUpperCase());

const files = fs.readdirSync(srcDir).filter(f => f.endsWith('.csv'));

for (const file of files) {
  const csv = fs.readFileSync(path.join(srcDir, file), 'utf-8');
  const parsed = Papa.parse(csv, { header: true, skipEmptyLines: true });
  if (parsed.errors.length) {
    console.error('CSV parse errors in', file, parsed.errors);
    process.exit(1);
  }

  const deckName = path.basename(file, '.csv');
  const camelDeckName = camelCase(deckName);

  let jsContent = `// THIS FILE IS AUTO-GENERATED BY scripts/build-decks.mjs. DO NOT EDIT.\n\n`;

  const imports = [];
  const cardObjects = [];

  parsed.data.forEach((row, idx) => {
    if (!row.image || !row.answer) {
      console.warn(`Row ${idx + 1} missing image or answer in ${file}`);
    }

    const imageName = `image${idx}`;
    const imagePath = `../assets/images/${row.image.trim().split('/').pop()}`;
    imports.push(`import ${imageName} from '${imagePath}';`);

    cardObjects.push(
      '  {\n' +
      `    image: ${imageName},
` +
      `    answer: ${JSON.stringify(row.answer.trim())},
` +
      `    alt: ${JSON.stringify((row.alt || '').trim())},
` +
      `    deck: ${JSON.stringify((row.deck || 'Default').trim())}
` +
      '  }'
    );
  });

  jsContent += imports.join('\n') + '\n\n';
  jsContent += `export const ${camelDeckName} = [${cardObjects.join(',\n')}
];\n`;

  const outName = `${deckName}.js`;
  fs.writeFileSync(path.join(outDir, outName), jsContent, 'utf-8');
  console.log('Wrote', path.join(outDir, outName));
}
