import fs from 'node:fs';
import path from 'node:path';
import Papa from 'papaparse';

const srcDir = path.resolve('decks');
const outDir = path.resolve('src/data');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

// Clean out old generated files before writing new ones
const oldFiles = fs.readdirSync(outDir).filter(f => f.endsWith('.js'));
for (const f of oldFiles) {
  fs.unlinkSync(path.join(outDir, f));
}

// Convert a string to a safe JS identifier in camelCase
const toSafeIdentifier = (str) =>
  str
    .replace(/[^a-zA-Z0-9]+/g, '_')   // non-alphanumeric → underscore
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase())  // underscoreChar → Char
    .replace(/^_|_$/g, '');            // trim leading/trailing underscores

// Convert a deck name to a kebab-case filename
const toFileName = (str) =>
  str
    .replace(/[^a-zA-Z0-9]+/g, '-')   // non-alphanumeric → hyphen
    .replace(/^-|-$/g, '')             // trim leading/trailing hyphens
    .toLowerCase();

const files = fs.readdirSync(srcDir).filter(f => f.endsWith('.csv'));

if (files.length === 0) {
  console.error('No CSV files found in decks/');
  process.exit(1);
}

// Collect all rows across all CSV files, grouped by deck column
const deckGroups = new Map();

for (const file of files) {
  const csv = fs.readFileSync(path.join(srcDir, file), 'utf-8');
  const parsed = Papa.parse(csv, { header: true, skipEmptyLines: true });
  if (parsed.errors.length) {
    console.error('CSV parse errors in', file, parsed.errors);
    process.exit(1);
  }

  for (const row of parsed.data) {
    if (!row.image || !row.answer) {
      console.warn(`Skipping row missing image or answer in ${file}:`, row);
      continue;
    }

    const deckName = (row.deck || 'Default').trim();
    if (!deckGroups.has(deckName)) {
      deckGroups.set(deckName, []);
    }
    deckGroups.get(deckName).push(row);
  }
}

if (deckGroups.size === 0) {
  console.error('No valid deck data found in CSV files');
  process.exit(1);
}

// Generate one JS module per deck
for (const [deckName, rows] of deckGroups) {
  const fileName = toFileName(deckName);
  const exportName = toSafeIdentifier(deckName);

  let jsContent = `// THIS FILE IS AUTO-GENERATED BY scripts/build-decks.mjs. DO NOT EDIT.\n\n`;

  const imports = [];
  const cardObjects = [];

  rows.forEach((row, idx) => {
    const imageName = `image${idx}`;
    const imageFile = row.image.trim().split('/').pop();
    imports.push(`import ${imageName} from '../assets/images/${imageFile}';`);

    const videoCell = (row.video || '').trim();
    let videoLiteral = 'null';
    if (videoCell) {
      const videoName = `video${idx}`;
      const videoFile = videoCell.split('/').pop();
      imports.push(`import ${videoName} from '../assets/videos/${videoFile}';`);
      videoLiteral = videoName;
    }

    cardObjects.push(
      '  {\n' +
      `    image: ${imageName},\n` +
      `    video: ${videoLiteral},\n` +
      `    answer: ${JSON.stringify(row.answer.trim())},\n` +
      `    alt: ${JSON.stringify((row.alt || '').trim())},\n` +
      `    deck: ${JSON.stringify(deckName)}\n` +
      '  }'
    );
  });

  jsContent += imports.join('\n') + '\n\n';
  jsContent += `export const ${exportName} = [\n${cardObjects.join(',\n')}\n];\n`;

  const outPath = path.join(outDir, `${fileName}.js`);
  fs.writeFileSync(outPath, jsContent, 'utf-8');
  console.log(`Wrote ${outPath} (${rows.length} cards)`);
}

console.log(`Generated ${deckGroups.size} deck modules from ${files.length} CSV files`);
